- name: Print info
  ansible.builtin.debug:
    msg:
    - "####################### ACS endpoints and credentials #########################"
    - "Your RHACS console is available at:"
    - "https://{{ r_acs_portal_route.resources[0].spec.host }}"
    - "RHACS portal username: admin"
    - "RHACS portal password: {{ ocp4_workload_rhacs_central_admin_password }}"
    - "###############################################################################"
