apiVersion: v1
stringData:
  rox_central_endpoint: "ROXCTL_CENTRAL_ENDPOINT"
  # The address:port tuple for StackRox Central (example - rox.stackrox.io:443)
  rox_api_token: "API_TOKEN"
  # StackRox API token with CI permissions
  # Refer to https://help.stackrox.com/docs/use-the-api/#generate-an-access-token
kind: Secret
metadata:
  name: roxsecrets
  namespace: pipeline-demo
type: Opaque