---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel8:latest

dependencies:
  galaxy: requirements.yml
  exclude:
    system:
      - openshift-clients
  
options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ./ansible.cfg
    dest: ./
 

additional_build_steps:
  prepend_base:
    - COPY _build/ansible.cfg /etc/ansible/ansible.cfg
  append_base:
    - RUN curl "https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip" -o "/terraform.zip"
    - RUN unzip /terraform.zip -d /terraform
    - RUN mv /terraform/terraform /bin
