- name: Day-1 Configure ARO cluster Playbook
  hosts: localhost
  vars_files:
    - vars/var_file.yaml
  module_defaults:
    community.okd.openshift_auth:
      host: "'{{ lookup('ansible.builtin.env', 'K8S_AUTH_HOST') }}'"
      validate_certs: no

  pre_tasks:
  - name: Wait for cluster operators
    kubernetes.core.k8s_info:
      api_version: config.openshift.io/v1
      kind: ClusterOperator
      wait: true
      wait_timeout: 1800
    register: cluster_operators
    until: cluster_operators.failed is not defined or not cluster_operators.failed
    retries: 10
    delay: 30

  tasks:
    - name: Authenticate to OpenShift cluster, install RHACS Operator, RHACS Central and RHACS Sensor
      block:
        - name: Setting up workload for user
          ansible.builtin.debug:
            msg: "Setting up RHACS for user ocp_username = {{ ocp_username }}"

        - name: Install Pipelines Operator
          ansible.builtin.include_role:
            name: install_operator
            tasks_from: install
          vars:
            install_operator_name: openshift-pipelines-operator
            install_operator_packagemanifest_name: "{{ ocp4_workload_pipelines_install_operator_packagemanifest_name }}" 
            install_operator_namespace: "{{ ocp4_workload_pipelines_install_operator_namespace }}"
            install_operator_channel: "{{ ocp4_workload_pipelines_install_operator_channel | default('') }}"
            install_operator_catalogsource_image_tag: "{{ ocp4_workload_pipelines_install_operator_catalog_source_tag | default('') }}"

        - name: Install ACS Operator
          ansible.builtin.include_role:
            name: install_operator
            tasks_from: install
          vars:
            install_operator_name: rhacs-operator
            install_operator_namespace: "{{ ocp4_workload_rhacs_install_operator_namespace }}"
            install_operator_channel: "{{ ocp4_workload_rhacs_install_operator_channel | default('') }}"
            # ignored install_operator_catalog: redhat-operators
            install_operator_use_catalog_snapshot: "{{ ocp4_workload_rhacs_install_operator_use_catalog_snapshot }}"
            # unknown install_operator_catalogsource_name: "{{ ocp4_workload_rhacs_install_operator_channel | default('') }}"
            install_operator_catalogsource_image_tag: "{{ ocp4_workload_rhacs_install_operator_catalog_source_tag | default('') }}"

        - name: Install ACS Central and Sensor
          ansible.builtin.include_role:
            name: install_acs
          vars:
            ocp4_workload_rhacs_central_admin_password: "{{ ocp4_workload_rhacs_central_admin_password }}"
            ACTION: create
       
      always:
        - name: If login succeeded, try to log out (revoke access token)
          when: openshift_auth.api_key is defined
          community.okd.openshift_auth:
            state: absent
            api_key: "{{ openshift_auth.api_key }}"

    - name: Get the ACS portal route
      tags: print_acs_info
      kubernetes.core.k8s_info:
        api_version: route.openshift.io/v1
        kind: Route
        name: central
        namespace: stackrox
      register: r_acs_portal_route

    - name: Print info
      tags: print_acs_info
      ansible.builtin.debug:
        msg:
        - "####################### ACS endpoints and credentials #########################"
        - "Your RHACS console is available at:"
        - "https://{{ r_acs_portal_route.resources[0].spec.host }}"
        - "RHACS portal username: admin"
        - "RHACS portal password: {{ ocp4_workload_rhacs_central_admin_password }}"
        - "###############################################################################"
